#YOUR_TUSHARE_KEY
tushare_key: "164e09ac8197f4a1c0990ffa595314871ce46380ac83aec693d7d3b9" 

#YOUR_BOCHA_KEY
bocha_key: "sk-d69c885fc7584cfbb87564c5ea6577f0" 

#YOUR_SERP_KEY
serp_key: "" 

#YOUR_FMP_KEY
fmp_key: "" 

#YOUR_FINNHUB_KEY
finnhub_key: "" 

# ==================================================
# LLM 配置说明 / LLM Configuration
# ==================================================
# 支持的 provider 选项 / Supported provider options:
#   - "openai"  : OpenAI官方API或兼容接口
#   - "gemini"  : Google Gemini API
#   - "ollama"  : 本地Ollama服务
#
# 配置示例 / Configuration examples:
#
# OpenAI:
#   provider: "openai"
#   base_url: "https://api.openai.com/v1"
#   api_key: "your_openai_api_key"
#   model_name: "gpt-4"
#
# DeepSeek (OpenAI compatible):
#   provider: "openai"
#   base_url: "https://api.deepseek.com"
#   api_key: "your_deepseek_api_key"
#   model_name: "deepseek-chat"
#
# 阶跃星辰 (OpenAI compatible):
#   provider: "openai"
#   base_url: "https://models-proxy.stepfun-inc.com/v1"
#   api_key: "your_stepfun_api_key"
#   model_name: "step-1o-turbo-vision"
#
# Google Gemini:
#   provider: "gemini"
#   base_url: "https://generativelanguage.googleapis.com/v1beta"
#   api_key: "your_gemini_api_key"
#   model_name: "gemini-2.0-flash"
#
# Local Ollama:
#   provider: "ollama"
#   base_url: "http://localhost:11434"
#   api_key: ""  # Ollama usually doesn't require an API key
#   model_name: "llama3.2:1b"
# ==================================================

llm:
  base_url: "https://api.deepseek.com"
  #YOUR_DEEPSEEK_API_KEY
  api_key: "sk-b51607cf268740f4aeb99501500b7d77"
  model_name: "deepseek-chat"

llm_thinking:
  base_url: "https://api.deepseek.com"
  #YOUR_DEEPSEEK_API_KEY
  api_key: "sk-b51607cf268740f4aeb99501500b7d77"
  model_name: "deepseek-reasoner"

vlm:
  base_url: "https://api.stepfun.com/v1"
  #YOUR_STEPFUN_API_KEY
  api_key: n906dO72odmAC1suLG8RHzX0G4YvHufK9RQdO0IDyPirwyrMNMLP9xlEuM5UVTmw
  model_name: "step-1o-turbo-vision"

# data_agents_config:
#   - agent_name: "sina_summary_agent"
#     data_source_list: 
#       - "data_source.sina_news_crawl.SinaNewsCrawl"
#   - agent_name: "thx_summary_agent"
#     data_source_list: 
#       - "data_source.thx_news_crawl.ThxNewsCrawl"
#   - agent_name: "price_market_agent"
#     data_source_list: 
#       - "data_source.price_market_akshare.PriceMarketAkshare"
#   - agent_name: "hot_money_agent"
#     data_source_list: 
#       - "data_source.hot_money_akshare.HotMoneyAkshare"

# research_agent_config:
#   belief_list_path: "config/belief_list.json"
#   max_react_step: 10
#   output_language: "中文"
#   tools:
#     - "tools.stock_symbol_search_akshare.stock_symbol_search"
#     - "tools.stock_selector_akshare.stock_selector"
#     - "tools.corp_info_akshare.company_financial_info"
#     - "tools.price_info_akshare.price_info"
#     - "tools.search_web.search_web"
#     - "tools.stock_summary_akshare.stock_summary"
#     - "tools.final_report.final_report"

market_config_file: "config/market_config.yaml"

# Tushare配套配置如下，请自行设置
# The configuration for Tushare is as follows, please set it up yourself.

data_agents_config:
  - agent_name: "thx_summary_agent"
    data_source_list: 
      - "data_source.thx_news_crawl.ThxNewsCrawl"
  - agent_name: "sina_summary_agent"
    data_source_list: 
      - "data_source.sina_news_crawl.SinaNewsCrawl"
  - agent_name: "price_market_agent"
    data_source_list: 
      - "data_source.price_market.PriceMarket"
  - agent_name: "hot_money_agent"
    data_source_list: 
      - "data_source.hot_money.HotMoney"

research_agent_config:
  belief_list_path: "config/belief_list.json"
  max_react_step: 10
  output_language: "中文"
  tools:
    - "tools.stock_symbol_search.stock_symbol_search_akshare"
    - "tools.stock_selector.stock_selector"
    - "tools.corp_info.company_financial_info"
    - "tools.price_info.price_info"
    - "tools.search_web.search_web"
    - "tools.stock_summary.stock_summary"
    - "tools.final_report.final_report"

system_language: "中文"

researcher_contest_config:
  contest_mode: False
  judger_config: llm
  num_judgers: 3
  window_m: 3
  window_n: 3
