# Single-symbol analysis config (CN-Stock)
# Usage:
#   set CONTEST_TRADE_CONFIG_FILE=./config_single.yaml
#   set CONTEST_TRADE_MARKET=CN-Stock
#   python scripts/single_symbol_signal.py --market CN-Stock --symbol 600519.SH --time "YYYY-MM-DD HH:MM:SS"

# ---- API KEYS (fill in as needed) ----
tushare_key: "164e09ac8197f4a1c0990ffa595314871ce46380ac83aec693d7d3b9"      # Optional for single-symbol flow with Akshare tools
bocha_key: "sk-d69c885fc7584cfbb87564c5ea6577f0"        # Optional (web search)
serp_key: ""
fmp_key: ""
finnhub_key: ""

# ---- LLM SETTINGS (REQUIRED) ----
# Fill your provider/base_url/api_key/model_name
llm:
  base_url: "https://api.deepseek.com"
  api_key: "sk-b51607cf268740f4aeb99501500b7d77"
  model_name: "deepseek-chat"

llm_thinking:
  base_url: "https://api.deepseek.com"
  api_key: "sk-b51607cf268740f4aeb99501500b7d77"
  model_name: "deepseek-reasoner"

vlm:
  base_url: "https://api.stepfun.com/v1"
  api_key: n906dO72odmAC1suLG8RHzX0G4YvHufK9RQdO0IDyPirwyrMNMLP9xlEuM5UVTmw
  model_name: "step-1o-turbo-vision"

# ---- Minimal data agents (optional; keep empty to speed up) ----
data_agents_config: []

# ---- Research agent tools (aliases first, Akshare fallbacks after) ----
research_agent_config:
  belief_list_path: "config/belief_list.json"
  max_react_step: 6
  output_language: "中文"
  tools:
    - "tools.aliases.stock_symbol_search"
    - "tools.aliases.stock_selector"
    - "tools.aliases.corp_info"
    - "tools.aliases.stock_quote"
    - "tools.aliases.stock_summary"
    - "tools.stock_symbol_search_akshare.stock_symbol_search"
    - "tools.stock_selector_akshare.stock_selector"
    - "tools.corp_info_akshare.company_financial_info"
    - "tools.price_info_akshare.price_info"
    - "tools.search_web.search_web"
    - "tools.stock_summary_akshare.stock_summary"
    - "tools.final_report.final_report"

market_config_file: "config/market_config.yaml"
system_language: "中文"

researcher_contest_config:
  contest_mode: False
  judger_config: llm
  num_judgers: 3
  window_m: 3
  window_n: 3
